title: Zhiwei Chen <br> 陈志威
position: Ph.D Student
affiliation: Xiamen University
email: zhiweichen.cn@gmail.com
keywords: Zhiwei Chen, computer vision, Xiamen university, XMU
# google_scholar:
# github_link:
# linkedin:
avatar: ./assets/img/avatar.png
# google_analytics:
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon.png
description: Zhiwei Chen is currently a Ph.D student in Xiamen university.
remote_theme: zhiweichen0012/zhiweichen0012.github.io
